team_names: ["Team A", "Team B", "Team C", "Team D"]
team_icons: ['dust.png', 'ring.png', 'dive.png', 'pharaoh.png']
segment_names : ["Goal 1", "Goal 2", "Goal 3", "Goal 4", "Goal 5", "Goal 6", "Goal 7", "Goal 8", "Goal 9", "Goal 10", "Goal 11", "Goal 12"]
font: "Roboto"
background_color : "#000000"
font_color : "#ffffff"
slider_border_color: "#cd1e1e"